//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBookDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CIB_PhoneBookEntities : DbContext
    {
        public CIB_PhoneBookEntities()
            : base("name=CIB_PhoneBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PhoneBook> PhoneBooks { get; set; }
        public virtual DbSet<PhoneBookEntry> PhoneBookEntries { get; set; }
    }
}
